### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by trebmuh** [sbadon122/ATLAS-06-Synthesizer#1]
I can't find under which license this software is released . Could you please add a LICENSE file?

**Comment by sbadon122** [comment]
Sure! I'll add one over the weekend.

**Comment by sbadon122** [comment]
@trebmuh https://github.com/sbadon122/ATLAS-06-Synthesizer/blob/master/LICENSE.md

**Comment by trebmuh** [comment]
Awesome.
Thanks for releasing it as a free software :+1:
